# Generated by Django 5.2 on 2025-04-10 03:50

import FileUploader.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Please enter CSV files only', upload_to='uploads/', validators=[FileUploader.models.FileValidator])),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FileUploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FileUploaders',
            },
        ),
    ]
