# Generated by Django 5.2 on 2025-04-09 14:29

import FileUploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='file',
            field=models.FileField(help_text='Please enter CSV files only', upload_to='uploads/', validators=[FileUploader.models.FileValidator]),
        ),
    ]
