# Generated by Django 5.2 on 2025-04-09 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploader', '0002_alter_fileuploader_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
